language:
 - c
os:
 - linux
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get -qq update
install:
 - sudo apt-get install -y libeina-dev
before_script:
 - mkdir build
 - cd build
 - cmake ..
script:
 - make
